[package]
name = "fpgrars"
version = "0.1.0"
authors = ["Leonardo Riether <leonardoalves8217@gmail.com>"]
edition = "2018"

[features]
show_ms = [] # show ms per frame in the window title

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
lazy_static = "1.4.0"

pixel-canvas = { git = "https://github.com/LeoRiether/pixel-canvas", branch = "develop" }
glium = "0.28.0"

nom = "5.1.2"

radix_trie = "0.0.9"
fnv = "1.0.7"

byteorder = "1.3.4"
