[package]
name = "fpgrars"
version = "0.1.0"
authors = ["Leonardo Riether <leonardoalves8217@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixel-canvas = { git = "https://github.com/LeoRiether/pixel-canvas", branch = "develop" }
glium = "0.28.0"
combine = "4.3.2"
