[package]
name = "fpgrars"
version = "0.1.0"
authors = ["Leonardo Riether <leonardoalves8217@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixel-canvas = "0.2.1"
glium = "0.26.0"

