name: Release v2

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        case:
          - target: x86_64-pc-windows-gnu
            output: target/x86_64-pc-windows-gnu/release/fpgrars.exe
            finalOutput: target/x86_64-pc-windows-gnu/release/fpgrars-x86_64-pc-windows-gnu.exe
          - target: x86_64-unknown-linux-gnu
            output: target/x86_64-unknown-linux-gnu/release/fpgrars
            finalOutput: target/x86_64-unknown-linux-gnu/release/fpgrars-x86_64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.case.target }}
          override: true
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.case.target }}
      - name: Rename output
        run: mv ${{ matrix.case.output }} ${{ matrix.case.finalOutput }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.case.finalOutput }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}